all:
  children:
    campus_demo:
      children:
        core:
        access:

    core:
      hosts:
        core01:
          ansible_host: 10.10.10.11
          device_role: core
          vendor: cisco
          platform: iosxe

    access:
      hosts:
        access01:
          ansible_host: 10.10.10.31
          device_role: access
          vendor: cisco
          platform: iosxe
        access02:
          ansible_host: 10.10.10.32
          device_role: access
          vendor: cisco
          platform: iosxe
